--CREATED
CREATE TABLE FLAT_ROOM (
    FLAT_ROOM_ID NUMBER NOT NULL,  --PK
    FLAT_ID NUMBER NOT NULL, --FK
    FLAT_ROOM_RENT DECIMAL(10, 2) NOT NULL,
    FLAT_ROOM_ISAVAIL CHAR(1) CHECK (FLAT_ROOM_ISAVAIL IN ('Y', 'N')) NOT NULL,
    CONSTRAINT PK_FLAT_ROOM PRIMARY KEY (FLAT_ROOM_ID),   --PK
    CONSTRAINT FK_FLAT_ROOM_FLAT FOREIGN KEY (FLAT_ID) REFERENCES FLAT(FLAT_ID)  --FK TO FLAT
);    
   
--CREATED
CREATE TABLE FLAT (
    FLAT_ID NUMBER NOT NULL,  -- PK
    FLAT_BUILDING_ID NUMBER NOT NULL, --FK 
    CONSTRAINT PK_FLAT PRIMARY KEY (FLAT_ID),  --PK
    CONSTRAINT FK_FLAT_FLAT_BUILDING_ID FOREIGN KEY (FLAT_BUILDING_ID) REFERENCES FLAT_BUILDING(FLAT_BUILDING_ID) --FK TO FLAT_BUILDING
);

--CREATED
CREATE TABLE FLAT_BUILDING (
    FLAT_BUILDING_ID NUMBER NOT NULL, --PK
    FLAT_BUILDING_STREET VARCHAR2(50) NOT NULL, 
    FLAT_BUILDING_CITY VARCHAR2(50) NOT NULL,
    FLAT_BUILDING_ZIP VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_FLAT_BUILDING PRIMARY KEY (FLAT_BUILDING_ID)  --PK
);

--CREATED
CREATE TABLE HALL_ROOM (
    HALL_ROOM_ID NUMBER NOT NULL,           --PK1
    HALL_ID NUMBER NOT NULL,                --FK1
    HALL_ROOM_RENT DECIMAL(10, 2) NOT NULL,
    HALL_ROOM_DIET VARCHAR2(20),            --FK2
    HALL_ROOM_ISAVAIL CHAR(1) CHECK (HALL_ROOM_ISAVAIL IN ('Y', 'N')) NOT NULL,
    ACCESS_REQ_ID NUMBER NOT NULL,    --FK3
    CONSTRAINT PK_HALL_ROOM PRIMARY KEY (HALL_ROOM_ID),          --PK
    CONSTRAINT FK_HALL_ROOM_HALL FOREIGN KEY (HALL_ID) REFERENCES HALL(HALL_ID), --FK TO HALL
    CONSTRAINT FK_DIET_HALL_ROOM FOREIGN KEY (HALL_ROOM_DIET) REFERENCES DIET(HALL_ROOM_DIET), --FK TO DIET
    CONSTRAINT FK_HALL_ACCESS_REQ FOREIGN KEY (ACCESS_REQ_ID) REFERENCES ACCESS_REQ(ACCESS_REQ_ID)  --FK TO ACCESS_REQ
    );

--CREATED
CREATE TABLE HALL (
    HALL_ID NUMBER NOT NULL,  --PK
    HALL_NAME NUMBER NOT NULL,  --FK
    CONSTRAINT FK_HALL_HALL_BUILDING FOREIGN KEY (HALL_NAME) REFERENCES HALL_BUILDING(HALL_NAME)  --FK TO HALL_BUILDING
);

--CREATED
CREATE TABLE DIET (
    HALL_ROOM_DIET VARCHAR2(50), --PK
    VEGAN CHAR(1) CHECK (VEGAN IN ('Y', 'N')) NOT NULL, 
    DAIRY_FREE CHAR(1) CHECK (DAIRY_FREE IN ('Y', 'N')) NOT NULL, 
    GLUTEN_FREE CHAR(1) CHECK (GLUTEN_FREE IN ('Y', 'N')) NOT NULL, 
    VEGETARIAN CHAR(1) CHECK (VEGETARIAN IN ('Y', 'N')) NOT NULL, 
    NA CHAR(1) CHECK (NA IN ('Y', 'N')) NOT NULL,
    CONSTRAINT PK_DIET PRIMARY KEY (HALL_ROOM_DIET)--PK
);

--HALL_BUILDING
CREATE TABLE HALL_BUILDING (
    HALL_NAME VARCHAR2(15) NOT NULL,  --PK
    STAFF_ID NUMBER NOT NULL,  --FK
    HALL_STREET VARCHAR2(50) NOT NULL,
    HALL_CITY VARCHAR2(50) NOT NULL,
    HALL_ZIP VARCHAR2(10) NOT NULL,
    HALL_AREA_CODE VARCHAR2(5) NOT NULL,
    HALL_PHONE NUMBER NOT NULL, 
    CONSTRAINT PK_HALL PRIMARY KEY (HALL_NAME),  --PK
    CONSTRAINT FK_HALL_STAFF FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)  --FK TO STAFF
);