
drop table INVOICE cascade constraints;

CREATE TABLE INVOICE (
    INV_ID NUMBER NOT NULL, -- PK
    LEASE_ID NUMBER NOT NULL, -- PK+FK REFERENCE LEASE TABLE
    INV_DUE DATE CONSTRAINT NN_INV_DUE NOT NULL,
    INV_SEM NUMBER(1) CONSTRAINT NN_INV_SEM NOT NULL,
    CONSTRAINT PK_INVOICE PRIMARY KEY (INV_ID, LEASE_ID),
    CONSTRAINT FK_INVOICE_LEASE FOREIGN KEY (LEASE_ID) REFERENCES LEASE(LEASE_ID)
);

CREATE TABLE INVOICE_LINE (
    INV_ID NUMBER NOT NULL,  -- FK REFERENCE INVOICE TABLE
    INV_LINE_ID NUMBER NOT NULL,  -- PK
    INV_PAID DATE CONSTRAINT NN_INV_PAID NOT NULL,
    INV_METHOD VARCHAR2(10) CONSTRAINT NN_INV_METHOD NOT NULL,
    INV_REMIND1 DATE CONSTRAINT NN_INV_REMIND1 NOT NULL,
    INV_REMIND2 DATE CONSTRAINT NN_INV_REMIND2 NOT NULL,
    CONSTRAINT PK_INVOICE_LINE PRIMARY KEY (INV_ID, INV_LINE_ID),
    CONSTRAINT FK_INVOICE_LINE_INV FOREIGN KEY (INV_ID) REFERENCES INVOICE (INV_ID)
)--hi

CREATE TABLE INSPECTION (
    INSP_ID NUMBER NOT NULL,  -- PK
    ACCOM_ID NUMBER NOT NULL,  -- FK REFERENCE ACCOMMODATION TABLE
    STAFF_ID NUMBER NOT NULL,  -- FK REFERENCE STAFF TABLE
    INSP_DATE DATE CONSTRAINT NN_INSP_DATE NOT NULL,
    INSP_RESULT CHAR(1) CHECK (INSP_RESULT IN ('T', 'F')) NOT NULL,  -- BOOLEAN TRUE/FALSE
    INSP_COMMENT VARCHAR2(50),
    CONSTRAINT PK_INSPECTION PRIMARY KEY (INSP_ID, ACCOM_ID, STAFF_ID),
    CONSTRAINT FK_INSPECTION_STAFF FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    CONSTRAINT FK_INSPECTION_ACCOM FOREIGN KEY (ACCOM_ID) REFERENCES ACCOMMODATION(ACCOM_ID)
);

CREATE TABLE STAFF (
    STAFF_ID NUMBER NOT NULL,  -- PK
    STAFF_FNAME VARCHAR2(20) CONSTRAINT NN_STAFF_FNAME NOT NULL,
    STAFF_LNAME VARCHAR2(20) CONSTRAINT NN_STAFF_LNAME NOT NULL,
    STAFF_ADDRESS VARCHAR2(100) CONSTRAINT NN_STAFF_ADDRESS NOT NULL,  
    STAFF_SEX VARCHAR2(10) CONSTRAINT NN_STAFF_SEX NOT NULL, -- SHOULD THIS BE NULLABLE? OR OPTION FOR "RATHER NOT SAY"
    CONSTRAINT PK_STAFF PRIMARY KEY (STAFF_ID)
);

CREATE TABLE STAFF_HISTORY (
    STAFF_ID NUMBER NOT NULL,  -- PK+FK REFERENCE STAFF TABLE
    STAFF_START DATE NOT NULL,  -- PK
    STAFF_END DATE,  -- NULLABLE ALLOWING FOR ONGOING POSITIONS
    STAFF_POSITION VARCHAR2(20) CONSTRAINT NN_STAFF_POSITION NOT NULL,
    STAFF_LOCATION VARCHAR2(20) CONSTRAINT NN_STAFF_LOCATION NOT NULL,
    DEG_DEPT VARCHAR2(50),  -- FK REFERECE DEGREE
    CONSTRAINT PK_STAFF_HISTORY PRIMARY KEY (STAFF_ID, STAFF_START),
    CONSTRAINT FK_STAFF_HISTORY_STAFF FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    CONSTRAINT FK_STAFF_HISTORY_DEPT FOREIGN KEY (DEG_DEPT) REFERENCES DEPARTMENT(DEG_DEPT)
);

CREATE TABLE UNIT (
    UNIT_NUM NUMBER NOT NULL,  -- PK
    UNIT_ISFURNISHED CHAR(1) CHECK (UNIT_ISFURNISHED IN ('T', 'F')) NOT NULL,  -- BOOLEAN TRUE/FALSE
    UNIT_MRENT NUMBER(10, 2) NOT NULL,  -- MONTHLY RENT 2DP
    ACC_ID NUMBER NOT NULL,  -- FK REFERENCE ACCOMMODATION TABLE
    UNIT_MEMCOUNT NUMBER(20) CONSTRAINT NN_UNIT_MEMCOUNT NOT NULL, --AMOUNT OF CURRENT MEMBERS
    CONSTRAINT PK_UNIT PRIMARY KEY (UNIT_NUM),
    CONSTRAINT FK_UNIT_ACCOM FOREIGN KEY (ACC_ID) REFERENCES ACCOMMODATION(ACC_ID)
);

CREATE TABLE MEMBER (
    MEM_ID NUMBER NOT NULL,  -- PK
    MEM_FNAME VARCHAR2(20) CONSTRAINT NN_MEM_FNAME NOT NULL,
    MEM_LNAME VARCHAR2(20) CONSTRAINT NN_MEM_LNAME NOT NULL,
    MEM_SEX VARCHAR2(10) CONSTRAINT NN_MEM_SEX NOT NULL, -- SHOULD THIS BE NULLABLE? OR OPTION FOR "RATHER NOT SAY"
    MEM_DOB DATE CONSTRAINT NN_MEM_DOB NOT NULL,  
    MEM_PHONE VARCHAR2(15),
    MEM_EMAIL VARCHAR2(50), 
    UNIT_NUM NUMBER NOT NULL,  -- FK REFERENCE UNIT TABLE
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEM_ID),
    CONSTRAINT FK_MEMBER_UNIT FOREIGN KEY (UNIT_NUM) REFERENCES UNIT(UNIT_NUM)
    CONSTRAINT CK_MEMBER_PHONE_EMAIL CHECK (MEM_PHONE IS NOT NULL OR MEM_EMAIL IS NOT NULL)  -- MAKE IT THAT THEY CAN EITHER GIVE EMAIL OR PHONE NUM
);

CREATE TABLE FLAT_ROOM (
    ACCOM_ID NUMBER NOT NULL,  -- PK+FK REFERENCE ACCOMMODATION TABLE
    FLAT_NUM NUMBER NOT NULL,  -- PK+FK FLAT TABLE
    STU_ID NUMBER,  -- FK REFERENCE STUDENT TABLE
    FLAT_ROOM_RENT NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_FLAT_ROOM PRIMARY KEY (ACCOM_ID, FLAT_NUM),
    CONSTRAINT FK_FLAT_ROOM_ACCOM FOREIGN KEY (ACCOM_ID) REFERENCES ACCOMMODATION(ACCOM_ID),
    CONSTRAINT FK_FLAT_ROOM_FLAT FOREIGN KEY (FLAT_NUM) REFERENCES FLAT(FLAT_NUM),
    CONSTRAINT FK_FLAT_ROOM_STUDENT FOREIGN KEY (STU_ID) REFERENCES STUDENT(STU_ID)
);

CREATE TABLE FLAT (
    FLAT_NUM NUMBER NOT NULL,  -- Pk
    FLAT_ADDRESS VARCHAR2(100) NOT NULL,
    FLAT_ROOM_AVAIL NUMBER(20) NOT NULL,  -- AVAILABLE ROOMS
    CONSTRAINT PK_FLAT PRIMARY KEY (FLAT_NUM)
);

CREATE TABLE HALL_ROOM (
    ACCOM_ID NUMBER NOT NULL,  -- PK+FK REFERENCE ACCOMMODATION TABLE
    HALL_NAME VARCHAR2(50) NOT NULL,  -- PK
    HALL_ROOM_NUM NUMBER(10) NOT NULL,
    HALL_ROOM_RENT NUMBER(10, 2) NOT NULL,
    HALL_ROOM_DIET VARCHAR2(50), 
    CONSTRAINT PK_HALL_ROOM PRIMARY KEY (ACCOM_ID, HALL_NAME),
    CONSTRAINT FK_HALL_ROOM_ACCOM FOREIGN KEY (ACCOM_ID) REFERENCES ACCOMMODATION(ACCOM_ID)
);-- SHOULD THIS HAVE STU_ID?

CREATE TABLE HALL (
    HALL_NAME VARCHAR2(50) NOT NULL,  -- PK
    HALL_ADDR VARCHAR2(100) NOT NULL,
    HALL_PHONE VARCHAR2(15) NOT NULL, 
    STAFF_ID NUMBER NOT NULL,  -- FK REFERENCE STAFF TABLE
    HALL_ROOM_AVAIL NUMBER(20) NOT NULL,  -- AVAILABLE ROOMS
    CONSTRAINT PK_HALL PRIMARY KEY (HALL_NAME),
    CONSTRAINT FK_HALL_STAFF FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

CREATE TABLE STUDENT (
    STU_ID NUMBER(10) NOT NULL,  -- PK
    STU_FNAME VARCHAR2(50) NOT NULL,
    STU_LNAME VARCHAR2(50) NOT NULL,
    STU_STREET VARCHAR2(100) NOT NULL,
    STU_CITY VARCHAR2(50) NOT NULL,
    STU_ZIP VARCHAR2(10) NOT NULL, 
    STU_DOB DATE NOT NULL,  
    STU_GENDER VARCHAR2(10),  -- GENDER/SEXUALITY
    STU_SEX VARCHAR2(10) CHECK (STU_SEX IN ('MALE', 'FEMALE')) NOT NULL,  -- BIOLOGICAL SEX + IS BOOLEAN
    STU_NATIONALITY VARCHAR2(50) NOT NULL,
    STU_STATUS VARCHAR2(10) CHECK (STU_STATUS IN ('PLACED', 'WAITING')) NOT NULL,  --BOOLEAN 
    STU_SMOKER CHAR(1) CHECK (STU_SMOKER IN ('T', 'F')) NOT NULL,  -- BOOLEAN T/F
    STU_ACCESS_REQ VARCHAR2(100),  -- ACCESSABILITY REQUIREMENTS
    STU_ADDITONAL_COMMENTS VARCHAR2(200), 
    DEGREE_ID NUMBER(10),  -- Fk REFERENCE DEGREE TABLE
    STAFF_ID NUMBER(20),  -- FK REFERENCE STAFF TABLE
    MOVEIN_DATE DATE,  -- FK REFERENCE LEASE TABLE
    MOVEOUT_DATE DATE,  -- FK REFERENCE LEASE TABLE
    CONSTRAINT PK_STUDENT PRIMARY KEY (STU_ID),
    CONSTRAINT FK_STUDENT_DEGREE FOREIGN KEY (DEGREE_ID) REFERENCES DEGREE(DEGREE_ID),
    CONSTRAINT FK_STUDENT_STAFF FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    CONSTRAINT FK_STUDENT_MOVEIN FOREIGN KEY (MOVEIN_DATE) REFERENCES LEASE(MOVEIN_DATE),
    CONSTRAINT FK_STUDENT_MOVEOUT FOREIGN KEY (MOVEOUT_DATE) REFERENCES LEASE(MOVEOUT_DATE)
);

CREATE TABLE DEPT (
    DEPT_ID NUMBER(10) NOT NULL,  -- PK
    DEPT_NAME VARCHAR2(100) CONSTRAINT NN_DEPT_NAME NOT NULL,
    CONSTRAINT PK_DEPT PRIMARY KEY (DEPT_ID)
);

CREATE TABLE DEGREE (
    DEG_ID NUMBER(10) NOT NULL,  -- PK
    DEPT_ID NUMBER(10) NOT NULL,  -- FK REFERENCE DEPT TABLE
    DEG_TITLE VARCHAR2(100) NOT NULL,  
    STAFF_ID NUMBER(20) NOT NULL,  -- FK REFERENCE STAFF TABLE
    STAFF_START DATE NOT NULL,  -- FK REFERENCE STAFF_HISTORY TABLE
    CONSTRAINT PK_DEGREE PRIMARY KEY (DEG_ID),
    CONSTRAINT FK_DEGREE_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPT(DEPT_ID),
    CONSTRAINT FK_DEGREE_STAFF FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    CONSTRAINT FK_DEGREE_STAFF_START FOREIGN KEY (STAFF_ID, STAFF_START) REFERENCES STAFF_HISTORY(STAFF_ID, STAFF_START)
);

CREATE TABLE NEXT_KIN (
    KIN_ID NUMBER(10) NOT NULL,  -- PK
    STU_ID NUMBER(10) NOT NULL,  -- FK REFERENCE STUDENT TABLE
    KIN_FNAME VARCHAR2(50) NOT NULL,
    KIN_LNAME VARCHAR2(50) NOT NULL,
    KIN_RELATIONSHIP VARCHAR2(50) NOT NULL,
    KIN_PHONE VARCHAR2(15),  
    KIN_EMAIL VARCHAR2(100),  
    CONSTRAINT PK_NEXT_KIN PRIMARY KEY (KIN_ID),
    CONSTRAINT FK_NEXT_KIN_STUDENT FOREIGN KEY (STU_ID) REFERENCES STUDENT(STU_ID),
    CONSTRAINT CK_KIN_PHONE_OR_EMAIL CHECK (KIN_PHONE IS NOT NULL OR KIN_EMAIL IS NOT NULL) -- MAKE IT THAT THEY CAN EITHER GIVE EMAIL OR PHONE NUM
);
